title: Cedric Moeller's Personal Website
email: cedric.moeller@uni-hamburg.de
baseurl: ""
url: "https://cedricmoeller.github.io"
github_username: cedricmoeller
author: Cedric Möller

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown

exclude:
  - README.md
